# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8a379433daea938b4b97f13605a304601600b9cff2eb7060d975a15d86f071fae7286d8f138994bc33f52c30f326eeff0d109a2e5743592481023c1f84c98100

test:
  secret_key_base: 41facc2324896f88bcbc93e02a6a5af7afbbab53c696aea231ef495aecb06ddfe9d15e1b8ded0fe8b613bf9d2674ce4981b73ee7ee0045a7bb0acb1fc8529f08

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
